### ISSUE TITLE
CanGenerateHashFromString is broken in JDK 9+ when string contains non-latin characters or +XX:-CompactStrings JVM flag is used

### ISSUE THREAD

**Issue by seanrohead** [alexandrnikitin/bloom-filter-scala#53]
CanGenerateHashFromStringByteArray, which is used for JDK9+, assumes that the string is stored using the UTF-8 character encoding and that the length of the underlying byte[] is the same as the length of the string. This assumption only holds true if the string only contains characters from the ISO-8859-1/Latin-1 character set. If the string contains other characters, the string is stored in the underlying byte array as UTF-16 characters and the length of the byte array is 2x the number of characters in the string. Additionally, it is possible to disable this storage optimization using the +XX:-CompactStrings JVM flag in which case all strings are stored as UTF-16 characters. See [here](http://openjdk.java.net/jeps/254) and [here](https://www.baeldung.com/java-9-compact-string) for more information.

**Comment by seanrohead** [comment]
I opened a pull request for this: https://github.com/alexandrnikitin/bloom-filter-scala/pull/54/files

**Comment by yarosman** [comment]
Have similar error but with `CanGenerateHashFromString`
```scala
Caused by: java.lang.ClassCastException: class [B cannot be cast to class [C ([B and [C are in module java.base of loader 'bootstrap')
    at bloomfilter.CanGenerateHashFrom$CanGenerateHashFromString$.generateHash(CanGenerateHashFrom.scala:27)
    at bloomfilter.CanGenerateHashFrom$CanGenerateHashFromString$.generateHash(CanGenerateHashFrom.scala:23)
```

**Comment by seanrohead** [comment]
@yarosman Are you using the latest version of the library? That issue was fixed in 0.13.0.

**Comment by yarosman** [comment]
> @yarosman Are you using the latest version of the library? That issue was fixed in 0.13.0.

@seanrohead We use 0.13.1

**Comment by seanrohead** [comment]
@yarosman Are you loading the bloom filter using serialization by any chance?

**Comment by yarosman** [comment]
@seanrohead Yes, we do. And I found that we don't use predefined method writeTo/readTo therefore we serialize with CanGenerateHashFrom, which dependent from java.
Or you have another explanation or idea ?

**Comment by yufan022** [comment]
> Have similar error but with `CanGenerateHashFromString`
> 
> ```scala
> Caused by: java.lang.ClassCastException: class [B cannot be cast to class [C ([B and [C are in module java.base of loader 'bootstrap')
>     at bloomfilter.CanGenerateHashFrom$CanGenerateHashFromString$.generateHash(CanGenerateHashFrom.scala:27)
>     at bloomfilter.CanGenerateHashFrom$CanGenerateHashFromString$.generateHash(CanGenerateHashFrom.scala:23)
> ```

Did you try use `CanGenerateHashFromStringByteArray`?
